package resources;
// Generated Mar 19, 2020 6:33:12 PM by Hibernate Tools 4.3.1



/**
 * Details generated by hbm2java
 */
public class Details  implements java.io.Serializable {


     private Integer iddetails;
     private String name;
     private String address;
     private String fax;
     private String tp;
     private String email;
     private String domain;
     private String image;
     private Byte status;

    public Details() {
    }

    public Details(String name, String address, String fax, String tp, String email, String domain, String image, Byte status) {
       this.name = name;
       this.address = address;
       this.fax = fax;
       this.tp = tp;
       this.email = email;
       this.domain = domain;
       this.image = image;
       this.status = status;
    }
   
    public Integer getIddetails() {
        return this.iddetails;
    }
    
    public void setIddetails(Integer iddetails) {
        this.iddetails = iddetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getTp() {
        return this.tp;
    }
    
    public void setTp(String tp) {
        this.tp = tp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


