package resources;
// Generated Mar 24, 2020 1:07:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GrnPayment generated by hbm2java
 */
public class GrnPayment  implements java.io.Serializable {


     private Integer grnPaymentId;
     private Grn grn;
     private PaymentType paymentType;
     private String date;
     private String time;
     private Double amount;
     private Integer status;
     private Set grnChequeDetailses = new HashSet(0);

    public GrnPayment() {
    }

	
    public GrnPayment(Grn grn, PaymentType paymentType) {
        this.grn = grn;
        this.paymentType = paymentType;
    }
    public GrnPayment(Grn grn, PaymentType paymentType, String date, String time, Double amount, Integer status, Set grnChequeDetailses) {
       this.grn = grn;
       this.paymentType = paymentType;
       this.date = date;
       this.time = time;
       this.amount = amount;
       this.status = status;
       this.grnChequeDetailses = grnChequeDetailses;
    }
   
    public Integer getGrnPaymentId() {
        return this.grnPaymentId;
    }
    
    public void setGrnPaymentId(Integer grnPaymentId) {
        this.grnPaymentId = grnPaymentId;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getGrnChequeDetailses() {
        return this.grnChequeDetailses;
    }
    
    public void setGrnChequeDetailses(Set grnChequeDetailses) {
        this.grnChequeDetailses = grnChequeDetailses;
    }




}


