package resources;
// Generated Mar 20, 2020 3:46:21 PM by Hibernate Tools 4.3.1



/**
 * InvoiceChequeDetails generated by hbm2java
 */
public class InvoiceChequeDetails  implements java.io.Serializable {


     private Integer invoiceChequeDetailsId;
     private InvoicePayment invoicePayment;
     private String type;
     private String chequeNo;
     private String chequeDate;
     private String bank;
     private String branch;
     private Double amount;
     private Integer status;

    public InvoiceChequeDetails() {
    }

	
    public InvoiceChequeDetails(InvoicePayment invoicePayment) {
        this.invoicePayment = invoicePayment;
    }
    public InvoiceChequeDetails(InvoicePayment invoicePayment, String type, String chequeNo, String chequeDate, String bank, String branch, Double amount, Integer status) {
       this.invoicePayment = invoicePayment;
       this.type = type;
       this.chequeNo = chequeNo;
       this.chequeDate = chequeDate;
       this.bank = bank;
       this.branch = branch;
       this.amount = amount;
       this.status = status;
    }
   
    public Integer getInvoiceChequeDetailsId() {
        return this.invoiceChequeDetailsId;
    }
    
    public void setInvoiceChequeDetailsId(Integer invoiceChequeDetailsId) {
        this.invoiceChequeDetailsId = invoiceChequeDetailsId;
    }
    public InvoicePayment getInvoicePayment() {
        return this.invoicePayment;
    }
    
    public void setInvoicePayment(InvoicePayment invoicePayment) {
        this.invoicePayment = invoicePayment;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getChequeNo() {
        return this.chequeNo;
    }
    
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }
    public String getChequeDate() {
        return this.chequeDate;
    }
    
    public void setChequeDate(String chequeDate) {
        this.chequeDate = chequeDate;
    }
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


