package resources;
// Generated Mar 19, 2020 6:33:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceId;
     private Customer customer;
     private User user;
     private Double total;
     private Double cash;
     private Double balance;
     private String date;
     private String time;
     private Double discount;
     private Double netTotal;
     private Integer status;
     private Set invoicePayments = new HashSet(0);
     private Set invoiceItems = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(Customer customer, User user) {
        this.customer = customer;
        this.user = user;
    }
    public Invoice(Customer customer, User user, Double total, Double cash, Double balance, String date, String time, Double discount, Double netTotal, Integer status, Set invoicePayments, Set invoiceItems) {
       this.customer = customer;
       this.user = user;
       this.total = total;
       this.cash = cash;
       this.balance = balance;
       this.date = date;
       this.time = time;
       this.discount = discount;
       this.netTotal = netTotal;
       this.status = status;
       this.invoicePayments = invoicePayments;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getCash() {
        return this.cash;
    }
    
    public void setCash(Double cash) {
        this.cash = cash;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getInvoicePayments() {
        return this.invoicePayments;
    }
    
    public void setInvoicePayments(Set invoicePayments) {
        this.invoicePayments = invoicePayments;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


