package resources;
// Generated Mar 19, 2020 6:33:12 PM by Hibernate Tools 4.3.1



/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer invoiceItemId;
     private Invoice invoice;
     private Stock stock;
     private Double cost;
     private Double unitPrice;
     private Double qty;
     private Double total;
     private Double discount;
     private Double netTotal;
     private Integer status;

    public InvoiceItem() {
    }

	
    public InvoiceItem(Invoice invoice, Stock stock) {
        this.invoice = invoice;
        this.stock = stock;
    }
    public InvoiceItem(Invoice invoice, Stock stock, Double cost, Double unitPrice, Double qty, Double total, Double discount, Double netTotal, Integer status) {
       this.invoice = invoice;
       this.stock = stock;
       this.cost = cost;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.total = total;
       this.discount = discount;
       this.netTotal = netTotal;
       this.status = status;
    }
   
    public Integer getInvoiceItemId() {
        return this.invoiceItemId;
    }
    
    public void setInvoiceItemId(Integer invoiceItemId) {
        this.invoiceItemId = invoiceItemId;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


