package resources;
// Generated Mar 20, 2020 3:46:21 PM by Hibernate Tools 4.3.1



/**
 * ItemStaffCost generated by hbm2java
 */
public class ItemStaffCost  implements java.io.Serializable {


     private Integer itemStaffCostId;
     private Items items;
     private ProductionSteps productionSteps;
     private Double cost;
     private Integer status;

    public ItemStaffCost() {
    }

	
    public ItemStaffCost(Items items, ProductionSteps productionSteps) {
        this.items = items;
        this.productionSteps = productionSteps;
    }
    public ItemStaffCost(Items items, ProductionSteps productionSteps, Double cost, Integer status) {
       this.items = items;
       this.productionSteps = productionSteps;
       this.cost = cost;
       this.status = status;
    }
   
    public Integer getItemStaffCostId() {
        return this.itemStaffCostId;
    }
    
    public void setItemStaffCostId(Integer itemStaffCostId) {
        this.itemStaffCostId = itemStaffCostId;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public ProductionSteps getProductionSteps() {
        return this.productionSteps;
    }
    
    public void setProductionSteps(ProductionSteps productionSteps) {
        this.productionSteps = productionSteps;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


