package resources;
// Generated Mar 20, 2020 3:46:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentType generated by hbm2java
 */
public class PaymentType  implements java.io.Serializable {


     private Integer paymentTypeId;
     private String name;
     private Integer status;
     private Set grnPayments = new HashSet(0);
     private Set invoicePayments = new HashSet(0);

    public PaymentType() {
    }

    public PaymentType(String name, Integer status, Set grnPayments, Set invoicePayments) {
       this.name = name;
       this.status = status;
       this.grnPayments = grnPayments;
       this.invoicePayments = invoicePayments;
    }
   
    public Integer getPaymentTypeId() {
        return this.paymentTypeId;
    }
    
    public void setPaymentTypeId(Integer paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getGrnPayments() {
        return this.grnPayments;
    }
    
    public void setGrnPayments(Set grnPayments) {
        this.grnPayments = grnPayments;
    }
    public Set getInvoicePayments() {
        return this.invoicePayments;
    }
    
    public void setInvoicePayments(Set invoicePayments) {
        this.invoicePayments = invoicePayments;
    }




}


