package resources;
// Generated Mar 20, 2020 3:46:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductionSteps generated by hbm2java
 */
public class ProductionSteps  implements java.io.Serializable {


     private Integer productionStepsId;
     private Items items;
     private String stepName;
     private Integer status;
     private Set itemStaffCosts = new HashSet(0);
     private Set productionStaffs = new HashSet(0);

    public ProductionSteps() {
    }

	
    public ProductionSteps(Items items) {
        this.items = items;
    }
    public ProductionSteps(Items items, String stepName, Integer status, Set itemStaffCosts, Set productionStaffs) {
       this.items = items;
       this.stepName = stepName;
       this.status = status;
       this.itemStaffCosts = itemStaffCosts;
       this.productionStaffs = productionStaffs;
    }
   
    public Integer getProductionStepsId() {
        return this.productionStepsId;
    }
    
    public void setProductionStepsId(Integer productionStepsId) {
        this.productionStepsId = productionStepsId;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public String getStepName() {
        return this.stepName;
    }
    
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getItemStaffCosts() {
        return this.itemStaffCosts;
    }
    
    public void setItemStaffCosts(Set itemStaffCosts) {
        this.itemStaffCosts = itemStaffCosts;
    }
    public Set getProductionStaffs() {
        return this.productionStaffs;
    }
    
    public void setProductionStaffs(Set productionStaffs) {
        this.productionStaffs = productionStaffs;
    }




}


