package resources;
// Generated Mar 28, 2020 12:36:20 AM by Hibernate Tools 4.3.1



/**
 * ProductionStaff generated by hbm2java
 */
public class ProductionStaff  implements java.io.Serializable {


     private Integer productionStaffId;
     private Production production;
     private ProductionSteps productionSteps;
     private Staff staff;
     private Double cost;
     private Double totalCost;
     private Integer status;

    public ProductionStaff() {
    }

	
    public ProductionStaff(Production production, ProductionSteps productionSteps, Staff staff) {
        this.production = production;
        this.productionSteps = productionSteps;
        this.staff = staff;
    }
    public ProductionStaff(Production production, ProductionSteps productionSteps, Staff staff, Double cost, Double totalCost, Integer status) {
       this.production = production;
       this.productionSteps = productionSteps;
       this.staff = staff;
       this.cost = cost;
       this.totalCost = totalCost;
       this.status = status;
    }
   
    public Integer getProductionStaffId() {
        return this.productionStaffId;
    }
    
    public void setProductionStaffId(Integer productionStaffId) {
        this.productionStaffId = productionStaffId;
    }
    public Production getProduction() {
        return this.production;
    }
    
    public void setProduction(Production production) {
        this.production = production;
    }
    public ProductionSteps getProductionSteps() {
        return this.productionSteps;
    }
    
    public void setProductionSteps(ProductionSteps productionSteps) {
        this.productionSteps = productionSteps;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


