package resources;
// Generated Mar 24, 2020 1:07:10 AM by Hibernate Tools 4.3.1



/**
 * ProductionRawItems generated by hbm2java
 */
public class ProductionRawItems  implements java.io.Serializable {


     private Integer productionRawItemsId;
     private Production production;
     private RawItems rawItems;
     private Double total;
     private Double cost;
     private Double totaCost;
     private Integer status;

    public ProductionRawItems() {
    }

	
    public ProductionRawItems(Production production, RawItems rawItems) {
        this.production = production;
        this.rawItems = rawItems;
    }
    public ProductionRawItems(Production production, RawItems rawItems, Double total, Double cost, Double totaCost, Integer status) {
       this.production = production;
       this.rawItems = rawItems;
       this.total = total;
       this.cost = cost;
       this.totaCost = totaCost;
       this.status = status;
    }
   
    public Integer getProductionRawItemsId() {
        return this.productionRawItemsId;
    }
    
    public void setProductionRawItemsId(Integer productionRawItemsId) {
        this.productionRawItemsId = productionRawItemsId;
    }
    public Production getProduction() {
        return this.production;
    }
    
    public void setProduction(Production production) {
        this.production = production;
    }
    public RawItems getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(RawItems rawItems) {
        this.rawItems = rawItems;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Double getTotaCost() {
        return this.totaCost;
    }
    
    public void setTotaCost(Double totaCost) {
        this.totaCost = totaCost;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


