package resources;
// Generated Mar 22, 2020 2:49:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RawItems generated by hbm2java
 */
public class RawItems  implements java.io.Serializable {


     private Integer rawItemsId;
     private MeasurementType measurementType;
     private String name;
     private String image;
     private Double rol;
     private Integer status;
     private Set productionRawItemses = new HashSet(0);
     private Set grnItems = new HashSet(0);
     private Set rawStocks = new HashSet(0);
     private Set itemsHasRawItemses = new HashSet(0);

    public RawItems() {
    }

	
    public RawItems(MeasurementType measurementType) {
        this.measurementType = measurementType;
    }
    public RawItems(MeasurementType measurementType, String name, String image, Double rol, Integer status, Set productionRawItemses, Set grnItems, Set rawStocks, Set itemsHasRawItemses) {
       this.measurementType = measurementType;
       this.name = name;
       this.image = image;
       this.rol = rol;
       this.status = status;
       this.productionRawItemses = productionRawItemses;
       this.grnItems = grnItems;
       this.rawStocks = rawStocks;
       this.itemsHasRawItemses = itemsHasRawItemses;
    }
   
    public Integer getRawItemsId() {
        return this.rawItemsId;
    }
    
    public void setRawItemsId(Integer rawItemsId) {
        this.rawItemsId = rawItemsId;
    }
    public MeasurementType getMeasurementType() {
        return this.measurementType;
    }
    
    public void setMeasurementType(MeasurementType measurementType) {
        this.measurementType = measurementType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Double getRol() {
        return this.rol;
    }
    
    public void setRol(Double rol) {
        this.rol = rol;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getProductionRawItemses() {
        return this.productionRawItemses;
    }
    
    public void setProductionRawItemses(Set productionRawItemses) {
        this.productionRawItemses = productionRawItemses;
    }
    public Set getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set grnItems) {
        this.grnItems = grnItems;
    }
    public Set getRawStocks() {
        return this.rawStocks;
    }
    
    public void setRawStocks(Set rawStocks) {
        this.rawStocks = rawStocks;
    }
    public Set getItemsHasRawItemses() {
        return this.itemsHasRawItemses;
    }
    
    public void setItemsHasRawItemses(Set itemsHasRawItemses) {
        this.itemsHasRawItemses = itemsHasRawItemses;
    }




}


