package resources;
// Generated Mar 24, 2020 1:07:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer staffId;
     private JobRoll jobRoll;
     private String name;
     private String mobile;
     private String nic;
     private String address;
     private Integer status;
     private Set productionStaffs = new HashSet(0);
     private Set users = new HashSet(0);

    public Staff() {
    }

	
    public Staff(JobRoll jobRoll) {
        this.jobRoll = jobRoll;
    }
    public Staff(JobRoll jobRoll, String name, String mobile, String nic, String address, Integer status, Set productionStaffs, Set users) {
       this.jobRoll = jobRoll;
       this.name = name;
       this.mobile = mobile;
       this.nic = nic;
       this.address = address;
       this.status = status;
       this.productionStaffs = productionStaffs;
       this.users = users;
    }
   
    public Integer getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }
    public JobRoll getJobRoll() {
        return this.jobRoll;
    }
    
    public void setJobRoll(JobRoll jobRoll) {
        this.jobRoll = jobRoll;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getProductionStaffs() {
        return this.productionStaffs;
    }
    
    public void setProductionStaffs(Set productionStaffs) {
        this.productionStaffs = productionStaffs;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


