package resources;
// Generated Mar 20, 2020 3:46:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer stockId;
     private Items items;
     private Double cost;
     private String date;
     private String time;
     private Double qty;
     private Double price;
     private Set invoiceItems = new HashSet(0);

    public Stock() {
    }

	
    public Stock(Items items) {
        this.items = items;
    }
    public Stock(Items items, Double cost, String date, String time, Double qty, Double price, Set invoiceItems) {
       this.items = items;
       this.cost = cost;
       this.date = date;
       this.time = time;
       this.qty = qty;
       this.price = price;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getStockId() {
        return this.stockId;
    }
    
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


